### ISSUE TITLE
problema project-archive GRAMMI

### ISSUE THREAD

**Issue by ClaraRuizG** [pablo-icm/emm#11]
He intentado añadir mi proyecto GRAMMI en project-archive copiando exactamente igual que el de acinas pero me da un error incomprensibleee

**Comment by pablo-icm** [comment]
Errores incomprensibles = Comillas. Cuando en los títulos hay carácteres especiales (como los `:` en el caso de tu proyecto), Hugo se vuelve loco al interpretar el fichero. Por eso es importante poner comillas en todos los campos y evitar este problema.

El commit 72aaa74 resuelve el issue.
