### ISSUE TITLE
Pronouns section needed

### ISSUE THREAD

**Issue by xabilopalf** [pablo-icm/emm#15]
Hi everyone, I tried to insert my **pronouns** (he/him) in as the `Display name`, but the result is quite ugly. 

Also I think it would be neccesary discuss it, and also make it clear that this IS a possibility, writting pronouns is obviously personal and optional, but it would be useful to avoid people feeling unseen. 

In my case, when searching for predoctoral scientist part, it appears like this:
<img width="238" alt="imagen" src="https://github.com/user-attachments/assets/f5f0ac62-99eb-4b29-bff7-a04183e465e5" />

and when looking it inside the profile it looks like this. 
<img width="394" alt="imagen" src="https://github.com/user-attachments/assets/c5e1f1be-3fc0-4267-aa94-cbde11016a5a" />

**Comment by pablo-icm** [comment]
There's a way that could add this section under the profile and would only be visible if the author adds this information on the front matter of `index.md`. It's in the to do list.

**Comment by pablo-icm** [comment]
I have added an optional field that you can include in your author `_index.md` page to specify the pronouns.

Follow this schema: 

```
pronouns: "*(xx/xx)*"
```

Closing.

**Comment by xabilopalf** [comment]
Thank you so much Pablo, even if this seems little, it really makes a huge change for many. 

You're the best!!!
